# config.yaml

input_folder: "docs"
output_folder: "results"
log_csv: "results/search_logs.csv"

ocr_enabled: true
ocr_languages:
  - en
  - hi

llm_model: "mistral-7b-instruct-v0.2"
llm_model_path: "models/mistral-7b-instruct-v0.2.Q4_K_M.gguf"
llm_context_window: 4096
llm_temperature: 0.7
llm_threads: 8
llm_gpu_layers: 35

embedding_model: "all-mpnet-base-v2"

abbreviation_mapping:
  Ltd: Limited
  Pvt: Private
  Inc: Incorporated
  Co: Company
  Mfg: Manufacturing

fuzzy_match_threshold: 85

summary_model: "t5-small"
summary_length: "medium"
rephrase_styles:
  - formal
  - simplified
  - bullet
  - conversational

feedback_enabled: true
feedback_storage: "results/feedback.json"